name: fmnist-resnet18
method: grid
parameters:
  lr:
    values:
      - 0.1
  weight_decay:
    values:
      - 2e-5
  seed:
    values:
      - 42
program: experiments/train.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --dataset=fmnist
  - --batch-size=64
  - --optimizer=sgd
  - --epochs=500
  - ${args}
